wallets:
  - private_key: "your_private_key_1"
    merkle_index: "your_merkle_index_1"
    merkle_proofs:
      - "merkle_proof_1_1"
      - "merkle_proof_1_2"
    token_amount: "token_amount_1"
  - private_key: "your_private_key_2"
    merkle_index: "your_merkle_index_2"
    merkle_proofs:
      - "merkle_proof_2_1"
      - "merkle_proof_2_2"
    token_amount: "token_amount_2"
target_address: "your_target_address"
rpc_url: "your_rpc_url"
approve: true
gather_all: false
only_approve: false
